[package]
authors = ["Sebastian Messmer <messmer@cryfs.org>"]
edition = "2021"
name = "cryfs-cppbridge"
version = "0.1.0"

[dependencies]
cryfs-blockstore = {path = "../blockstore"}
cxx = {version = "^1.0.71", features = ["c++14"]}
async-trait = "^0.1.56"
futures = "^0.3.21"
anyhow = "^1.0.58"
log = "^0.4.17"
lazy_static = "^1.4.0"
env_logger = "^0.9.0"
tokio = {version = "^1.20.0", features = ["fs", "io-util", "rt-multi-thread", "macros"]}
libc = "^0.2.138"

[build-dependencies]
cxx-build = "^1.0.71"

[lib]
crate-type = ["staticlib"]
