[package]
authors = ["Sebastian Messmer <messmer@cryfs.org>"]
edition = "2021"
name = "cryfs-cppbridge"
version = "0.1.0"

[dependencies]
anyhow = "^1.0.58"
async-trait = "^0.1.56"
cryfs-blobstore = {path = "../blobstore"}
cryfs-blockstore = {path = "../blockstore"}
cryfs-cryfs = {path = "../cryfs"}
cryfs-utils = {path = "../utils"}
cxx = {version = "^1.0.71", features = ["c++14"]}
env_logger = "^0.9.0"
futures = "^0.3.21"
lazy_static = "^1.4.0"
libc = "^0.2.138"
log = "^0.4.17"
tokio = {version = "^1.20.0", features = ["fs", "io-util", "rt-multi-thread", "macros"]}

[build-dependencies]
cxx-build = "^1.0.71"

[lib]
crate-type = ["staticlib"]
