[package]
authors = ["Sebastian Messmer <messmer@cryfs.org>"]
edition = "2021"
name = "cryfs-cryfs"
version = "0.1.0"

[dependencies]
anyhow = "^1.0.68"
async-trait = "^0.1.60"
binary-layout = "^3.1.3"
binrw = "^0.10.0"
cryfs-blobstore = {path = "../blobstore"}
cryfs-blockstore = {path = "../blockstore"}
cryfs-utils = {path = "../utils"}
derive_more = "^0.99.17"
futures = "^0.3.25"
thiserror = "^1.0.38"
