[package]
authors = ["Sebastian Messmer <messmer@cryfs.org>"]
edition = "2021"
name = "cryfs-blockstore"
version = "0.1.0"

[dependencies]
anyhow = "^1.0.65"
async-trait = "^0.1.56"
base64 = "^0.13.0"
binary-layout = "^3.1.1"
binrw = "^0.10.0"
cryfs-utils = {path = "../utils"}
errno = "^0.2.8"
futures = "^0.3.21"
hex = "^0.4.3"
lockable = {git = "https://github.com/smessmer/lockable", rev = "f075ea07795aa3882fe1d1764459d36183e5b2ca", features = ["lru"]}
log = "^0.4.17"
lzzzz = "^1.0.3"
mockall = {version = "^0.11.1", optional = true}
rand = "^0.8.5"
sysinfo = "^0.24.6"
thiserror = "^1.0.31"
tokio = {version = "^1.20.0", features = ["fs"]}
tokio-stream = {version = "^0.1.9", features = ["fs"]}

[target.'cfg(not(any(target_os = "unknown", target_arch = "wasm32")))'.dependencies]
libc = "^0.2.126"

[target.'cfg(windows)'.dependencies]
winapi = {version = "^0.3.9", features = ["fileapi"]}

[dev-dependencies]
common_macros = "^0.1.1"
cryfs-utils = {path = "../utils", features = ["testutils"]}
generic-array = "^0.14.5"
mockall = "^0.11.1"
tempdir = "^0.3.7"

[features]
testutils = ["mockall"]
