[package]
authors = ["Sebastian Messmer <messmer@cryfs.org>"]
edition = "2021"
name = "cryfs-blockstore"
version = "0.1.0"

[dependencies]
aead = "^0.4.3"
aes-gcm = {version = "^0.9.4", features = ["std"]}
anyhow = "^1.0.58"
async-trait = "^0.1.56"
base64 = "^0.13.0"
binary-layout = {git = "https://github.com/smessmer/binary-layout", rev = "f49fa855ab8619cd4d68a2852692d1e17f914ca6"}
binread = {version = "^2.2.0", features = ["const_generics"]}
binwrite = "^0.2.1"
chacha20poly1305 = "^0.9.1"
cipher = "^0.4.3"
clru = "^0.5.0"
common_macros = "^0.1.1"
env_logger = "^0.9.0"
errno = "^0.2.8"
futures = "^0.3.21"
generic-array = "^0.14.5"
hex = "^0.4.3"
itertools = "^0.10.3"
lazy_static = "^1.4.0"
log = "^0.4.17"
paste = "^1.0.7"
rand = "^0.8.5"
region = "^3.0.0"
ring = "^0.16.20"
sodiumoxide = "^0.2.7"
static_assertions = "^1.1.0"
sysinfo = "^0.24.6"
thiserror = "^1.0.31"
tokio = {version = "^1.20.0", features = ["fs", "io-util", "rt-multi-thread", "macros"]}
tokio-stream = {version = "^0.1.9", features = ["fs"]}
# https://github.com/jeromefroe/lru-rs/pull/128
lru = {git = "https://github.com/smessmer/lru-rs.git", rev = "ec021658cd7d48deb88226ad31bb6f3f33e16575"}
# owning_ref_rs uses v0.4.1 with https://github.com/Kimundi/owning-ref-rs/pull/80 and parts of https://github.com/Kimundi/owning-ref-rs/pull/56
lockable = {git = "https://github.com/smessmer/lockable", rev = "c43a9a864bd746f501dbbb9104119c2f480b6e8e", features = ["lru"]}
owning_ref_lockable = "^0.4.2"
tokio-util = "^0.7.3"

[target.'cfg(not(any(target_os = "unknown", target_arch = "wasm32")))'.dependencies]
libc = "^0.2.126"

[target.'cfg(windows)'.dependencies]
winapi = {version = "^0.3.9", features = ["fileapi"]}

[dev-dependencies]
criterion = "^0.3.6"
generic-tests = "^0.1.2"
mockall = "^0.11.1"
tempdir = "^0.3.7"

[[bench]]
harness = false
name = "crypto"

[[bench]]
harness = false
name = "path"
